@echo off
title GLITCH CITY - Launching...
cd /d "%~dp0"
echo Starting GLITCH CITY...
start "" "C:\Users\AADI\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe\Godot_v4.7.2-stable_win64.exe" --path .
